# Generated by Django 3.2 on 2023-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elevator', '0002_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floornumber',
            field=models.IntegerField(unique=True),
        ),
    ]
