# Generated by Django 3.2 on 2023-07-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elevator', '0003_alter_floor_floornumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnning', models.CharField(choices=[('Start', 'Start'), ('Stop', 'Stop')], default='Start', max_length=5)),
                ('door_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Close', max_length=5)),
                ('move_status', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], default='Up', max_length=4)),
                ('lift_status', models.BooleanField(default=True)),
                ('current_status', models.IntegerField(blank=True, null=True)),
                ('lift_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elevator.lift')),
                ('whichfloor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elevator.floor')),
            ],
        ),
    ]
