# Generated by Django 3.2 on 2023-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elevator', '0004_liftdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floornumber',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
